### ISSUE TITLE
[DOC] - Fill out Privacy Policy

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/BeccaBot#135]
# Incorrect Documentation

## Describe the error

The [Privacy Policy](https://github.com/nhcarrigan/discord-bot/blob/main/PRIVACY.md) is currently very bare-bones and probably does not cover all expected cases.

## Expected information

This should be expanded on with any relevant or necessary information. This can be done in one PR, or in multiple.

**Comment by LandonLloyd** [comment]
I can do this one!

**Comment by nhcarrigan** [comment]
All yours! I'll assign you when I get home

**Comment by LandonLloyd** [comment]
Sweet thanks!

**Comment by LandonLloyd** [comment]
Assign me again! XD

**Comment by LandonLloyd** [comment]
Thanks! I am gonna make this good.
