### ISSUE TITLE
[REQUEST] - React feature!

### ISSUE THREAD

**Issue by LandonLloyd** [nhcarrigan/BeccaBot#145]
# Feature Request
You should make a command i.e. |react :emoji: :username: So what the feature would do is make a reaction on someone's last comment. So say nhcarrigan says something funny on discord. |react :rofl: :nhcarrigan:. It would then make a :rofl: reaction on your last comment on discord.
## Is your feature request related to a problem? Please describe:
No. It is just a cool feature that would make discord a lot better.
I am always frustrated when I want to react to something but then I have to do so much work to actually do it.
## Describe the solution you'd like
A |react feature/command
You should make a command i.e. |react :emoji: :username: So what the feature would do is make a reaction on someone's last comment. So say nhcarrigan says something funny on discord. |react :rofl: :nhcarrigan:. It would then make a :rofl: reaction on your last comment on discord.
## Additional context
Thanks!

**Comment by YashKandalkar** [comment]
I'd like work on this 😃

**Comment by nhcarrigan** [comment]
I've assigned you! 😁

**Comment by nhcarrigan** [comment]
I think this feature will be held off for now. We are going to close this issue.
