### ISSUE TITLE
[REQUEST] - Blocked User feature

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/BeccaBot#146]
# Feature Request

## Is your feature request related to a problem? Please describe:

Currently there is no feature to restrict access to bot commands on a per-user basis. 

## Describe the solution you'd like

This issue will take two steps:
1. Create an array to store IDs of blocked users. This should be stored in the `.env` file to allow updates without requiring a rebuild. 
2. Confirm the user calling a command is not blocked before running the command.

**Comment by YashKandalkar** [comment]
Hey! I came across this repo, I'd like to contribute but have some questions.
> Create an array to store IDs of blocked users. This should be stored in the .env file to allow updates without requiring a rebuild.
Will updating the env file be enough? I don't know how the bot is hosted but after every restart/rebuild the ids stored in env file will be lost right? Or is the data preserved?

**Comment by nhcarrigan** [comment]
I'd be happy to assign this to you!

The bot is hosted on Heroku, so `.env` values are preserved across builds. However, I'm actually thinking a better approach would be to store an array of blocked IDs in the `config.json` file, then have the bot check if the message author is included in that array. If it is, skip the command (or send a message response explaining the user is blocked).

**Comment by YashKandalkar** [comment]
AFAIK the heroku restarts it's dynos often (once a day?), so editing files doesn't work, the changes will disappear after restart. And [this](https://stackoverflow.com/questions/34738619/set-heroku-environment-variable-without-restarting-app) SO question suggests that the app will rebuild if we update the env vars. The best option is to use a database (heroku has a postgres db with 10k rows limit).

**Comment by nhcarrigan** [comment]
The bot is already configured to a MongoDB instance, so we could leverage that existing database. 

However, this does not necessarily need to be a command that a user can call, but a configuration option that can be set manually in the code base (for people running their own instance of the bot). 

Adding it as a command would be something to do in #144 - so server admins can lock out users on a per-server basis.

**Comment by YashKandalkar** [comment]
Oh so for this issue we just have to add IDs in `config.json`. Got it, will make a PR on 1st 😄
