### ISSUE TITLE
[REQUEST] - Refactor User Command

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/BeccaBot#149]
# Feature Request

## Is your feature request related to a problem? Please describe:

Received confirmation that the data displayed in the user command is not considered "private" under Discord ToS. The user command can be refactored to take a mention again.

## Describe the solution you'd like

The user command should take an optional parameter and return information for the mentioned user. If no parameter is provided, it should return information for the message author.

**Comment by lokerhp** [comment]
Hai, can i do this?

**Comment by nhcarrigan** [comment]
Sure! I'll assign you 😁
