### ISSUE TITLE
[BUG] When a bot leave a server

### ISSUE THREAD

**Issue by danielsolartech** [nhcarrigan/BeccaBot#200]
# Bug Report

## Describe the bug

I just think if I kick the bot of my server, the data collected by the bot to the database continues existing instead be deleted from the database.

- Level information
- Hearts reactions (User id)
- Commands usage
- Settings (Roles and channels)

**Comment by nhcarrigan** [comment]
We could probably stick a database cleanup inside the `onGuildDelete` event. 🤔

**Comment by danielsolartech** [comment]
Yes @nhcarrigan , I forgot add the file to solve this 😅
