### ISSUE TITLE
[CHORE] - Fix Workflow

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/BeccaBot#272]
# Chore Request

## Describe the work

#271 corrected the broken CI workflow and now the tests are actually being run on pull requests. However, the `onMessage.spec.ts` run is throwing errors in the CI flow, but not on a local instance. 

This will need to be investigated and fixed - temporarily, I've changed the file to `onMessage.spec.ts.txt` so the work is preserved but does not interfere with the CI.

**Comment by adprasad** [comment]
How do you see the error?

**Comment by nhcarrigan** [comment]
https://github.com/nhcarrigan/BeccaBot/pull/275/checks?check_run_id=1350739448

Here's a broken CI run
